---
title: ""
---

<br>
<br>

## Articles scientifiques - Peer-reviewed journal articles

2021\. [Parliamentary Debates in Canada (1901-2015)](https://www.cambridge.org/core/journals/canadian-journal-of-political-science-revue-canadienne-de-science-politique/article/parliamentary-debates-in-canada-19012015/22DFF060A0BCE5BEC96E36EC075325D0/share/bfc29308e8885c740f53d76a57ecd30490926975). Canadian Journal of Political Science. Avec/With Jean‐François Godbout & Christopher Cochrane.

2019\. [Candidate Authenticity: "To thine own self be true"](https://link.springer.com/article/10.1007/s11109-019-09589-y). Political Behavior. Avec/With Dieter Stiers, Jac Larner, John Kenny, Sofia Breitenstein Gomis & Michael Lewis-Beck.

2017\. [About time: age, period, and cohort effects on support for Quebec sovereignty](https://onlinelibrary.wiley.com/doi/pdf/10.1111/nana.12378). Nations and Nationalism. Avec/With Ruth Dassonneville & Jean‐François Godbout. 


## Chapitre d'ouvrage collectif - Book chapter

2018\. [L'analyse des scrutins parlementaires](https://www.larciergroup.com/fr/traite-d-etudes-parlementaires-2018-9782802760481.html). Dans/In Olivier Rozenberg & Eric Thiers (eds.), Traité d'études parlementaires, coll. Etudes parlementaires, Bruxelles: Larcier. Avec/With Jean-François Godbout. 

## Texte d'opinion - Op-ed article

2017\. [Quebec’s ethnic nationalism in perspective](http://policyoptions.irpp.org/magazines/february-2017/quebecs-ethnic-nationalism-in-perspective/). Policy Options. Avec/With Alexie Labelle. 
